"""Deterministic illustrative embeddings + PCA-to-3D (Task 8.12).

Feeds the 3D scatter on the "How LLMs Use Tokens" page. Exactly as
illustrative as that page's existing 2D "embedding lookup" table
(`_illustrative_embedding` in `6_How_LLMs_Use_Tokens.py`) — these are NOT
learned parameters of any trained model, just fixed-seed random vectors,
reduced to 3 dimensions with a plain NumPy PCA (via SVD) purely so they can
be plotted. No GloVe/word2vec, no download, no PyTorch/scikit-learn.
"""

from __future__ import annotations

import numpy as np

#: 8-16 dimensions per the task's spec; midpoint chosen so the PCA step
#: below is doing real dimensionality reduction (12 -> 3), not a no-op.
DEFAULT_EMBEDDING_DIMENSIONS = 12


def generate_illustrative_embeddings(
    token_ids: list[int], dimensions: int = DEFAULT_EMBEDDING_DIMENSIONS
) -> np.ndarray:
    """One fixed, reproducible random vector per token ID, stacked into an `(N, dimensions)` array.

    Each row is generated by its own `numpy.random.default_rng(seed=token_id)`
    — a fresh, independent generator seeded by that ID — so the same token
    ID always produces the same vector across Streamlit reruns, without any
    shared global random state. `token_ids=[]` returns an empty
    `(0, dimensions)` array.
    """
    if not token_ids:
        return np.zeros((0, dimensions))
    return np.array(
        [
            np.random.default_rng(seed=token_id).uniform(-1.0, 1.0, size=dimensions)
            for token_id in token_ids
        ]
    )


def pca_3d(vectors: np.ndarray) -> np.ndarray:
    """Reduce `vectors` (`N, D`) to 3 principal components (`N, 3`) via SVD, pure NumPy.

    Standard PCA: mean-center the data, then project onto the first 3
    right-singular vectors of the centered matrix. `vectors` with fewer
    than 3 rows (or fewer than 3 usable components once centered, e.g. a
    single distinct token) still returns an `(N, 3)` array — missing
    components are zero-filled rather than raised, so a very short input
    text still renders a (degenerate) point cloud instead of crashing the
    page.
    """
    n_rows = vectors.shape[0]
    if n_rows == 0:
        return np.zeros((0, 3))
    centered = vectors - vectors.mean(axis=0, keepdims=True)
    _, _, vt = np.linalg.svd(centered, full_matrices=False)
    n_components = min(3, vt.shape[0])
    projected = centered @ vt[:n_components].T
    if n_components < 3:
        projected = np.hstack([projected, np.zeros((n_rows, 3 - n_components))])
    return projected
